### ISSUE TITLE
missing include limits.h

### ISSUE THREAD

**Issue by dkorunic** [haproxy/httpterm#1]
Hi,
INT_MAX requires limits.h include which seems to be omitted.

Thanks,
D.

**Comment by lukastribus** [comment]
Note that this is an unofficial fork here. The real project is at (GIT URL):
http://git.1wt.eu/git/httpterm.git

Which contains the fix 5912aa41 for this:
http://www.haproxy.org/git?p=httpterm.git;a=commit;h=5912aa41ed22932da5b9bed698bc1eab2de129e2
